name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build with CMake
        run: |
          mkdir _build
          cd _build
          cmake ..
          cmake --build .
